### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Syntaxis-Web** [jonybur/f1-telemetry-client#35]
**Describe the bug**
I followed the documentation and it didn't work

**To Reproduce**
Do what you said to do
You also can not pick an IP address it defaults to 0.0.0.0

**Expected behavior**
Get lap data

**Comment by jonybur** [comment]
Hello @Syntaxis-Web, what's not working? Do you get an error? How are you setting up the project?

**Comment by ForzaMark** [comment]
I could not get it to work following the documentation (first `npm install f1-telemetry-client`, then `npm run start`) either. Although after cloning this repository, running `npm install` then `npm run start` everything worked fine

**Comment by ForzaMark** [comment]
Perhabs it would be useful to mention that you have to enable upd telemetry to on in game
https://www.simracingtelemetry.com/help/F12019/

**Comment by Syntaxis-Web** [comment]
Hello, sorry to reopen this but I am trying again nearly a year later ;). Same issues, yes UDP telemetry is enabled in the game I'm not that stupid. Everything is installed correctly and I've even reinstalled the package multible times. I am receiving this error:
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE 0.0.0.0:20777
←[90m    at dgram.js:339:20←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:85:21)←[39m
Emitted 'error' event on Socket instance at:
←[90m    at dgram.js:341:14←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:85:21)←[39m {
  errno: ←[32m'EADDRINUSE'←[39m,
  code: ←[32m'EADDRINUSE'←[39m,
  syscall: ←[32m'bind'←[39m,
  address: ←[32m'0.0.0.0'←[39m,
  port: ←[33m20777←[39m
}

**Comment by jonybur** [comment]
Please check if the script is already running; otherwise try to find the task that is using the port 20777 and kill it. Closing this issue. Thanks.
